projectName: security-workshop
owner:
  email: john.doe@companyemail.com
  name: John Doe
participants:
  flights_booked: true
  hotel_booked: true
  invites_sent: true
  staff_logistics: true
program:
  documentation: false
  scope: true
  speakers: true
  targets_acquired: true
secondary:
  after_party: true
  av: false
  awards: true
  swag: true
  tools: true
  venue: true
